### ISSUE TITLE
feat: reddit is fun user agent change 

### ISSUE THREAD

**Issue by DaviddH** [ReVanced/revanced-patches-template#2727]
### Application

Reddit is fun

### Issue

Reddit is fun is now blocked based on the user agent so it seems, just using oauth client id change patch is not enough anymore 

### Patch

Patch to change the user agent reddit is fun is using, if possible mirroring something like a recent chrome version so it can't be detected by redddit

### Motivation

Patching this would make the app work again and not force users to use the terrible first party app

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
The official client's user agent could be tried.

**Comment by Ma-ve** [comment]
The info Reddit shows:

>>> whoa there, pardner!
reddit's awesome and all, but you may have a bit of a problem.

Make sure your User-Agent is not empty, is something unique and descriptive and try again. if you're supplying an alternate User-Agent string, try changing back to default as that can sometimes result in a block.

You can read Reddit's Terms of Service here.

if you think that we've incorrectly blocked you or you would like to discuss easier ways to get the data you want, please contact us at this email address.

when contacting us, please include your ip address which is: x.x.x.x and reddit account

**Comment by saveriol** [comment]
We need to be able the redirect url of the apis too.

Otherwise "redditisfun://auth" is the next thing they'll block.

**Comment by oSumAtrIX** [comment]
No, this is a local protocol handler.

**Comment by calexil** [comment]
following this to see if this gets worked out, rif is bae

**Comment by LogicalError007** [comment]
For me reddit is down on browsers too but it happened gradually, first Rif then infinity and then on browsers.

**Comment by Sculas** [comment]
> No, this is a local protocol handler.

Still identifiable data you're giving to Reddit. Believe me, if they made a tool to delete all API keys with the RIF UA, it's really easy to do the same for the redirect URI.

**Comment by oSumAtrIX** [comment]
It would be unconventional protocol to blacklist redirect URIs whereas checking for the user agent is not.

**Comment by Sculas** [comment]
Convention this, convention that. No person follows all of the laws perfectly. If they're gonna block you from using RIF, they'll use every solution they have at hand, and that includes blocking a redirect URI.

**Comment by oSumAtrIX** [comment]
I highly doubt this. Protocols are conventional because they are being used and unless Reddit starts to do detective work such as blacklisting the redirect uri patching what is conventionally checked for will suffice.

**Comment by Sculas** [comment]
> unless Reddit starts to do detective work

So removing API keys by a specific UA isn't "detective work" already?

**Comment by oSumAtrIX** [comment]
Yes, it is a conventional protocol. The user agent is primarily used for authentication.

**Comment by ltclarke** [comment]
Any way to change the user-agent via a local proxy?

**Comment by oSumAtrIX** [comment]
This should fix it: [`b9aaf61` (#2679)](https://github.com/ReVanced/revanced-patches/pull/2679/commits/b9aaf610ad9f1f45a72265a3782d2cf996020139)

**Comment by GitPat-138** [comment]
> This should fix it: [`b9aaf61` (#2679)](https://github.com/ReVanced/revanced-patches/pull/2679/commits/b9aaf610ad9f1f45a72265a3782d2cf996020139)

Hasn't fixed it for me, even after updating ReVanced manager and downloading newest patches.

**Comment by oSumAtrIX** [comment]
Everyone else testing it has reported that it works now.

**Comment by GitPat-138** [comment]
> Everyone else testing it has reported that it works now.

I still get Error: Forbidden when trying to open RIF. Have patched 3 times now, 2 from new.

**Comment by dgw** [comment]
Yep, updated Manager and repatched RIF, boom. Thank you all!

**Comment by GitPat-138** [comment]
> Everyone else testing it has reported that it works now.

Works now, thank you. Took a while I guess for ReVanced to pull the patch

**Comment by zimmertr** [comment]
Wooo! 🎆

**Comment by sanga000** [comment]
Using the new patch on Recanced Manager gives me syntax error (I'm on Android 10 if that helps)

Screnshot: https://files.catbox.moe/pyj52f.jpg

Using it on Revancify gives me "No Client ID Provided" error, despite having already filled in the OAuth Client ID in Patch Options

Screenshot: https://files.catbox.moe/cpt4cl.jpg

**Comment by calexil** [comment]
forgive my ignorance but how to I install this patch?

**Comment by adambennett** [comment]
Working for me now as well. Thanks for the super quick fix oSumAtrIX

**Comment by DaviddH** [comment]
Can confirm it works again now, thanks for the quick fix!

**Comment by RobinZergiebel** [comment]
You guys are awesome, thank you for your work!

**Comment by kollerbud** [comment]
Rif is down again, showing error forbidden like yesterday 8/2

**Comment by RobinZergiebel** [comment]
> Rif is down again, showing error forbidden like yesterday 8/2

Still working for me.

**Comment by nandryshak** [comment]
Thanks, this fixed it for me. 

> I highly doubt this. Protocols are conventional because they are being used conventionally and unless Reddit starts to do detective work such as blacklisting the redirect uri patching what is conventionally checked for will suffice.

I'm definitely with @Sculas on this one. Clearly they are doing some type of detective work. Changing the UA to one that clearly identifies the app as being modded by revanced seems like an absolutely terrible idea. At best, it's super easy for them to block access again. At worse, all users could get banned for TOS violations or reddit could send revanced a cease and desist. Identifying as revanced removes plausible deniability. 

It should be changed to a generic browser UA.

**Comment by Sculas** [comment]
@nandryshak The UA was changed, that's what fixed it for now. What hasn't changed is the redirect URI, and that's still something we pass to Reddit. We're giving it to them on a silver platter, waiting for them to start blocking the redirect URI as well. But oSumAtrIX doubts it because of "convention" and because of that they wouldn't do such a thing. Reddit blocking the UA is not a coincidence, so I don't wanna come back to this issue saying "I told you so".

**Comment by calexil** [comment]
again...how do I 'install' this patch?

**Comment by GitPat-138** [comment]
> again...how do I 'install' this patch?

Update ReVanced manager and re-patch RIF

**Comment by Mushin** [comment]
> @Sculas Yes, I definitely agree with you on all of that.
> 
> I just wanted to add to your point by mentioning that the new "more convincing" UA (wording from the commit msg) is _also_ a silver platter, because it's clearly indicating that the app has been modified by revanced. Previously when it was just a random number, it did not identify the app as modded.
> 
> Now that reddit can identify apps and users as revanced users, it risks getting the users banned for ToS violations and risks revanced getting a C&D, because now there is no longer any plausible deniability that the users are using revanced.

Could this not be solved by generating a random user agent at the time of patching?

**Comment by nandryshak** [comment]
> > @Sculas Yes, I definitely agree with you on all of that.
> > I just wanted to add to your point by mentioning that the new "more convincing" UA (wording from the commit msg) is _also_ a silver platter, because it's clearly indicating that the app has been modified by revanced. Previously when it was just a random number, it did not identify the app as modded.
> > Now that reddit can identify apps and users as revanced users, it risks getting the users banned for ToS violations and risks revanced getting a C&D, because now there is no longer any plausible deniability that the users are using revanced.
> 
> Could this not be solved by generating a random user agent at the time of patching?

That's already what the old code did. It just generated a random number. I think it should be changed to a generic browser UA and I'm making a PR with an example.

**Comment by calexil** [comment]
oh thank god, rif is working again....how would I ever moderate from my toilet without it....

**Comment by oSumAtrIX** [comment]
@Sculas You are free to patch it yourself. I will remain with my best bet until anything speaks against it.

**Comment by oSumAtrIX** [comment]
@nandryshak It already creates a compliant UA.

**Comment by calexil** [comment]
> @nandryshak It already creates a compliant UA.

good to know, I am not trying to run afoul of the reddit tos, I just want an app that isn't ass for moderating

**Comment by zimmertr** [comment]
I also believe the app should instead advertise itself as Chrome or something less identifiable.

**Comment by PitchforkAssistant** [comment]
What about letting users specify their own user agent? That would let concerned users come up with custom user agents that have some plausible deniability. If the user doesn't provide it, just fall back to Chrome or a random number.

**Comment by dgw** [comment]
> fall back to Chrome

I don't know how accurate this is any more considering how long ago the repo was archived, but:

> **NEVER lie about your user-agent.** This includes spoofing popular browsers and spoofing other bots.
> — https://github.com/reddit-archive/reddit/wiki/API

**Comment by DaviddH** [comment]
Seems like it is blocked again by reddit, getting the same error again now. (Was working before after applying the latest spoof client app)

**Comment by zimmertr** [comment]
Still working for me. I anticipate people are going to be paranoid about this fix for a while lol.

**Comment by oSumAtrIX** [comment]
Open a new issue, spamming "works" and "doesn't work" doesn't help.
